name=LGFX_FabGL_Combined
version=1.0.0
author=Clemente Garcia [foky26@gmail.com](mailto:foky26@gmail.com)
maintainer=foky26 [foky26@gmail.com](mailto:foky26@gmail.com)
sentence=Interface panel to FabGL for LovyanGFX
paragraph=Allows using LovyanGFX with FabGL VGA interface on ESP32-based boards.
category=Display
url=https://github.com/foky26/Lgfx_FabGL_Combined
architectures=esp32
includes=LovyanGFX.h,FabGL.h
license=MIT


